// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GYMappWeb.Models;

public partial class TblMembershipType
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int MemberShipTypesId { get; set; }

    public string Name { get; set; } = null!;
    public int MembershipDuration { get; set; }
    public int Price { get; set; }
    public int invitationCount { get; set; }
    public string? Description { get; set; }
    public int FreezeCount { get; set; }
    public bool IsActive { get; set; }
    public int TotalFreezeDays { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }

    public int? GymBranchId { get; set; }

    [ForeignKey("GymBranchId")]
    public virtual GymBranch? GymBranch { get; set; }
    public virtual ICollection<TblOffer> TblOffers { get; set; } = new List<TblOffer>();
    public virtual ICollection<TblUserMemberShip> TblUserMemberShips { get; set; } = new List<TblUserMemberShip>();
}