// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GYMappWeb.Models;

public partial class TblMemberShipFreeze
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int MemberShipFreezeId { get; set; }

    public int UserMemberShipId { get; set; }
    public DateOnly FreezeStartDate { get; set; }
    public DateOnly FreezeEndDate { get; set; }
    public string? Reason { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public int? GymBranchId { get; set; }

    [ForeignKey("GymBranchId")]
    public virtual GymBranch? GymBranch { get; set; }
    public virtual TblUserMemberShip UserMemberShip { get; set; } = null!;
}