// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GYMappWeb.Models;

public partial class TblOffer
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int OffId { get; set; }

    public string OfferName { get; set; } = null!;
    public int DiscountPrecentage { get; set; }
    public int MemberShipTypesId { get; set; }
    public bool IsActive { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public int? GymBranchId { get; set; }

    [ForeignKey("GymBranchId")]
    public virtual GymBranch? GymBranch { get; set; }
    public virtual TblMembershipType MemberShipTypes { get; set; } = null!;
    public virtual ICollection<TblUserMemberShip> TblUserMemberShips { get; set; } = new List<TblUserMemberShip>();
}