// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GYMappWeb.Models;

public partial class TblUser
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserId { get; set; }

    public int UserCode { get; set; }
    public string UserName { get; set; } = null!;
    public string UserPhone { get; set; } = null!;
    public bool IsActive { get; set; }
    public string? Notes { get; set; }
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    public virtual ICollection<TblUserMemberShip> TblUserMemberShips { get; set; } = new List<TblUserMemberShip>();
}