// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GYMappWeb.Models;

public partial class TblUserMemberShip
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserMemberShipId { get; set; }

    public DateOnly StartDate { get; set; }
    public DateOnly EndDate { get; set; }
    public bool IsActive { get; set; }
    public int? invitationUsed { get; set; }
    public int? TotalFreezedDays { get; set; }
    public int? OffId { get; set; }
    public int UserId { get; set; }
    public int MemberShipTypesId { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public virtual TblMembershipType MemberShipTypes { get; set; } = null!;
    public virtual TblOffer? Off { get; set; }
    public virtual ICollection<TblMemberShipFreeze> TblMemberShipFreezes { get; set; } = new List<TblMemberShipFreeze>();
    public virtual TblUser User { get; set; } = null!;
}